M48
; DRILL file {KiCad (6.0.5-0)} date Wednesday, November 02, 2022 at 01:33:36 am
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-02T01:33:36-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.711
%
G90
G05
T1
X81.75Y-63.7
X81.75Y-65.7
X92.25Y-63.7
X92.25Y-65.7
T0
M30
