M48
; DRILL file {KiCad (6.0.4-0)} date Wednesday, May 04, 2022 at 08:02:47 pm
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-05-04T20:02:47-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.711
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.100
%
G90
G05
T1
X82.354Y-56.9
X82.354Y-58.9
X82.354Y-63.55
X82.354Y-65.55
T2
X84.7Y-43.1
X89.3Y-43.1
T0
M30
